#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspwmbar &
#polybar example &

#feh --bg-scale ~/Pictures/Wallpapers/alena-aenami-million-little-pieces-1k.jpg

WALLPAPERS_DIR=~/Pictures/Wallpapers/
feh --bg-scale "$WALLPAPERS_DIR"$(ls "$WALLPAPERS_DIR" | sort --random-sort | head -1)
#feh --bg-scale "$WALLPAPERS_DIR"/5tvDrjx.png

external_monitor=$(xrandr --query | grep 'HDMI-1')
if [[ $external_monitor == *" connected "* ]]; then
    bspc monitor eDP-1 -d 1 2 3 4 5 #6 7 8 9 10
    bspc monitor HDMI-1 -d 6 7 8 9 10
else
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
fi




bspc config border_width         3
bspc config window_gap           8
bspc config border_radius        5

bspc config split_ratio           0.50
bspc config borderless_monocle    false
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config click_to_focus        true

# Dual monitors disconnected
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focused_border_color '#7F1131'
#bspc config focused_border_color '#bdae93'
bspc config normal_border_color '#458588'
bspc config presel_feedback_color '#FF5E8E'

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bash $HOME/.config/polybar/launch.sh &
